- name: Load additional variable files if defined
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/variables/{{ item.path }}/{{ item.name }}{{ item.suffix | default(omit) }}.yml"
    name: "{{ item.name }}"
  loop: "{{ variable_files }}"
  when: variable_files is defined
