- name: Load additional variable files if defined
  ansible.builtin.include_vars:
    file: "{{ ansible_playbook_directory }}/variables/{{ item.path }}/{{ item.name }}.yml"
    name: "{{ item.name }}"
  loop: "{{ variable_files }}"
  when: variable_files is defined
